// Standalone uptime monitor for closeconnect.in -- deliberately its own
// tiny Worker with its own wrangler.jsonc, not wired into the main app's
// OpenNext build. The main app's worker.js is regenerated by
// `opennextjs-cloudflare build` on every deploy, so anything hand-added to
// it would be silently wiped out the next time someone runs `npm run
// deploy` -- a separate Worker can't be affected by that, and (just as
// important) a bug in the monitor itself can never take the real site
// down with it.
//
// Runs on a cron trigger (see wrangler.jsonc) and only emails on a STATE
// CHANGE (up -> down, or down -> up), tracked in KV -- not on every tick,
// which would otherwise mean one email every 5 minutes for the entire
// length of an outage.
const CHECK_URLS = [
  "https://closeconnect.in/",
  "https://closeconnect.in/communities",
  "https://closeconnect.in/events",
  "https://closeconnect.in/login",
  "https://closeconnect.in/create",
];

const TIMEOUT_MS = 10_000;
const STATE_KEY = "status";

async function checkUrl(url) {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(TIMEOUT_MS) });
    return { url, ok: res.ok, status: res.status };
  } catch (err) {
    return { url, ok: false, status: null, error: String(err) };
  }
}

async function sendAlert(env, subject, html) {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${env.RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: "Close.Connect Monitor <notifications@closeconnect.in>",
      to: env.ADMIN_EMAIL,
      subject,
      html,
    }),
  });
  if (!res.ok) {
    console.error(`Resend send failed: ${res.status} ${await res.text()}`);
  } else {
    console.log(`Resend send succeeded: ${res.status} ${await res.text()}`);
  }
}

function formatFailures(failures) {
  return `<ul>${failures
    .map((f) => `<li>${f.url} — ${f.status ?? "no response"}${f.error ? ` (${f.error})` : ""}</li>`)
    .join("")}</ul>`;
}

export async function runCheck(env) {
  const results = await Promise.all(CHECK_URLS.map(checkUrl));
  const failures = results.filter((r) => !r.ok);
  const previousState = await env.MONITOR_STATE.get(STATE_KEY);

  if (failures.length > 0) {
    if (previousState !== "down") {
      await sendAlert(
        env,
        `🔴 closeconnect.in: ${failures.length}/${results.length} checks failing`,
        `<p>The following pages are not responding normally:</p>${formatFailures(failures)}`,
      );
    }
    await env.MONITOR_STATE.put(STATE_KEY, "down");
  } else {
    if (previousState === "down") {
      await sendAlert(env, "✅ closeconnect.in is back up", "<p>All checked pages are responding normally again.</p>");
    }
    await env.MONITOR_STATE.put(STATE_KEY, "up");
  }

  return results;
}

export default {
  async scheduled(_event, env, _ctx) {
    await runCheck(env);
  },
  // Manual trigger for testing/on-demand checks -- hitting this Worker's
  // own URL runs the same check immediately and reports the result,
  // without waiting for (or needing) a state-change email.
  async fetch(_request, env, _ctx) {
    const results = await runCheck(env);
    return new Response(JSON.stringify(results, null, 2), {
      headers: { "content-type": "application/json" },
    });
  },
};
